In [1]:
## Exemplo de aula

from sklearn import tree
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

x = [[0,0], [0,1], [1,0], [1,1]]
y = [0, 1, 1, 0]

features_names = ['x1', 'x2']
target_names = ['falso', 'verdadeiro']

arv = tree.DecisionTreeClassifier()
arv = arv.fit(x,y)

arv.predict([[0.,1.]])

r = tree.export_text(arv)
print(r)
dot_data = tree.export_graphviz(arv, out_file = None, filled=False, rounded = True, impurity = True, feature_names=features_names, class_names = target_names)

graph = graphviz.Source(dot_data)
graph.render("graph")

|--- feature_1 <= 0.50
|   |--- feature_0 <= 0.50
|   |   |--- class: 0
|   |--- feature_0 >  0.50
|   |   |--- class: 1
|--- feature_1 >  0.50
|   |--- feature_0 <= 0.50
|   |   |--- class: 1
|   |--- feature_0 >  0.50
|   |   |--- class: 0



'graph.pdf'

In [ ]:
from sklearn.datasets imort 

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split ## Importando biblioteca que separa o dataset de treino e de teste aleatoriamente e automática
from sklearn import tree
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

##Preparing Dataset

data = load_breast_cancer()

label_names = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']

print(features)
print(labels)

arv = tree.DecisionTreeClassifier() ## Criando a árvore de decisão para classificar o tipo de câncer
arv = arv.fit(features, labels) ## Training the model to give us the classification

g = []
for i in range(0, len(features)):
    r = arv.predict([features[i]]) ## predicting the results according to the inicial dataset.
    g.append(r)
    
G = np.array(g)

print(G)
    
def accuracy(test, test_labels):
    t = 0
    for i in range (0, len(test)):
        x = arv.predict([test[i]]) - test_labels[i]
        if x == 1:
            t = t + x
        elif x == -1:
            t = t - x
    return ((t/len(test))+1)*100

cr = accuracy(features, labels)
acrr = accuracy_score(labels, G)
print("A assertividade da arvore ficou em", cr,"%")
print("A assertividade da arvore ficou em", acrr,"%")

    

##dot_data = tree.export_graphviz(arv, out_file = None, filled=False, rounded = True, impurity = True)

##graph = graphviz.Source(dot_data)
##graph.render("graphv2")


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [98]:
print(arv)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')


In [38]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split ## Importando biblioteca que separa o dataset de treino e de teste aleatoriamente e automática
from sklearn import tree
import pandas as pd
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

##Preparing Dataset

data = load_breast_cancer()

label_names = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']

train, test, train_labels, test_labels = train_test_split(features, labels, test_size = 0.2, random_state=42)

##print(train)
##print (test)
##print(train_labels)
##print(test_labels)

arv = tree.DecisionTreeClassifier() ## Criando a árvore de decisão para classificar o tipo de câncer
arv = arv.fit(train, train_labels) ## Training the model to give us the classification

predicted_train = arv.predict(train)

g = []
for i in range(0, len(test)):
    r = arv.predict([test[i]]) ## predicting the results according to the inicial dataset.
    g.append(r)

G = np.array(g)


def accuracy(test, test_labels):
    t = 0
    for i in range (0, len(test)):
        x = arv.predict([test[i]]) - test_labels[i]
        if x == 1:
            t = t + x
        elif x == -1:
            t = t - x
    return abs((abs(t/len(test))-1))*100

cr = accuracy(test, test_labels)
cr_train = accuracy(train, train_labels)
acrr = accuracy_score(test_labels, G)
acrr_train = accuracy_score(train_labels, predicted_train)

print("A assertividade da arvore ficou em", cr,"%")
print("A assertividade da arvore ficou em", cr_train,"%")
print("A assertividade da arvore ficou em", acrr,"%")
print("A assertividade da arvore ficou em", acrr_train,"%")



A assertividade da arvore ficou em [92.10526316] %
A assertividade da arvore ficou em 100.0 %
A assertividade da arvore ficou em 0.9210526315789473 %
A assertividade da arvore ficou em 1.0 %


In [4]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split ## Importando biblioteca que separa o dataset de treino e de teste aleatoriamente e automática
from sklearn import tree
from sklearn.metrics import accuracy_score
import numpy as np
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

data = load_breast_cancer()

label_names = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']

train, valid, train_labels, valid_labels = train_test_split(features, labels, test_size = 0.4, random_state=42)
validr, test, validr_labels, test_labels = train_test_split(valid, valid_labels, test_size = 0.5, random_state=42)


j=[]
for i in range (2, 101):
    arv = tree.DecisionTreeClassifier(max_depth = i)
    arv = arv.fit(train, train_labels)
    predicted_results = arv.predict(validr)
    results = accuracy_score(predicted_results, validr_labels)
    j.append(results)
    
j = np.array(j)
idx = np.argmax(j) + 2 ## Putting the index value into the same range of the parameters used on the max_depth input
print("A profundidade escolhida é a:", idx)

treinamento = np.concatenate((train, validr))
treinamento_labels = np.concatenate((train_labels, validr_labels))

arvt = tree.DecisionTreeClassifier(max_depth = idx)
arvt = arvt.fit(treinamento, treinamento_labels)
predicted_test = arvt.predict(test)
final_results = accuracy_score(predicted_test, test_labels)*100
print("A acuraciedade do nosso modelo ficou de", final_results, "%")

n = []
for l in range (2, 101):
    for m in range (0, 10):
        arvt = tree.DecisionTreeClassifier(max_depth = l)
        arvt = arvt.fit(treinamento, treinamento_labels)
        predicted_test = arvt.predict(test)
        final_results = ((accuracy_score(test_labels, predicted_test)*100)-l)
        n.append(final_results)
   
n = np.array(n)
print(n.spape)
print(n)
##n = np.mean(n)

##print("O desempenho corrigido pela maior quantidade de profundidade é:", n, "%")




A profundidade escolhida é a: 2
A acuraciedade do nosso modelo ficou de 92.98245614035088 %


AttributeError: 'numpy.ndarray' object has no attribute 'spape'

In [14]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split ## Importando biblioteca que separa o dataset de treino e de teste aleatoriamente e automática
from sklearn import tree
from sklearn.metrics import accuracy_score
import numpy as np
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

data = load_breast_cancer()

label_names = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']

train, valid, train_labels, valid_labels = train_test_split(features, labels, test_size = 0.4, random_state=42)
validr, test, validr_labels, test_labels = train_test_split(valid, valid_labels, test_size = 0.5, random_state=42)


j=[]
for i in range (2, 101):
    for m in range(0,10): 
        arv = tree.DecisionTreeClassifier(max_depth = i)
        arv = arv.fit(train, train_labels)
        predicted_results = arv.predict(validr)
        results = ((accuracy_score(predicted_results, validr_labels)*100)-i)
        j.append(results)
    
j = np.array(j)
##print(j)
idx = (np.argmax(j)/10) + 2 ## Qualquer valor que estiver entre esse o range de 2-3, representa profundidade igual a 2 e etc
print("A profundidade escolhida é a:", idx)

treinamento = np.concatenate((train, validr))
treinamento_labels = np.concatenate((train_labels, validr_labels))

arvt = tree.DecisionTreeClassifier(max_depth = 2)
arvt = arvt.fit(treinamento, treinamento_labels)
predicted_test = arvt.predict(test)
final_results = accuracy_score(predicted_test, test_labels)*100
print("A acuraciedade do nosso modelo ficou de", final_results, "%")

dot_data = tree.export_graphviz(arvt, out_file = None, filled=False, rounded = True, impurity = True)

graph = graphviz.Source(dot_data)
graph.render("graphv6")



A profundidade escolhida é a: 2.1
A acuraciedade do nosso modelo ficou de 92.98245614035088 %


'graphv6.pdf'